/* 
	Marco Rodriguez -->
  	07-26-12 -->
 	Project 4 -->
	MIU 1207 -- >
*/

// JSON file 

var json = {
	"contact1": {
		"fname": 		["First Name:", "Mike"],
		"lname": 		["Last Name:", "Cook"],
		"email": 		["Email:", "mcook@gmail.com"],
		"date": 		["Date:", "2012-06-18"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Corvette"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "You guys Rock!"]
	},
	"contact2": {
		"fname": 		["First Name:", "Albert"],
		"lname": 		["Last Name:", "Bing"],
		"email": 		["Email:", "abing@gmail.com"],
		"date": 		["Date:", "2012-06-16"],
		"make": 		["Make:", "BMW"],
		"car": 			["Car:", "M5"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "10's"],
		"hp": 			["Horse Power:", "500HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Auto"],
		"ltech": 		["Referred from LS1Tech.com:", "No"],
		"comments": 	["Any Comments:", "No thanks!"]
	},
	"contact3": {
		"fname": 		["First Name:", "Mike"],
		"lname": 		["Last Name:", "Cook"],
		"email": 		["Email:", "mcook@gmail.com"],
		"date": 		["Date:", "2012-06-18"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Corvette"],
		"caramount": 	["How many cars do you own:", "3"],
		"fastest": 		["Fastest Time:", "11's"],
		"hp": 			["Horse Power:", "500HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "You guys Rock!"]
	},
	"contact4": {
		"fname": 		["First Name:", "Jon"],
		"lname": 		["Last Name:", "Collie"],
		"email": 		["Email:", "jcollie@yahoo.com"],
		"date": 		["Date:", "2012-06-20"],
		"make": 		["Make:", "Ford"],
		"car": 			["Car:", "Mustang Cobra"],
		"caramount": 	["How many cars do you own:", "3"],
		"fastest": 		["Fastest Time:", "8's"],
		"hp": 			["Horse Power:", "600HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Stangs Rock!"]
	},
	"contact5": {
		"fname": 		["First Name:", "Gilbert"],
		"lname": 		["Last Name:", "Cortez"],
		"email": 		["Email:", "gilbertc81@gmail.com"],
		"date": 		["Date:", "2012-06-21"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Corvette"],
		"caramount": 	["How many cars do you own:", "1"],
		"fastest": 		["Fastest Time:", "11's"],
		"hp": 			["Horse Power:", "500HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Auto"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Been on Tech for almost 10 years now!"]
	},
	"contact6": {
		"fname": 		["First Name:", "Jessica"],
		"lname": 		["Last Name:", "Barton"],
		"email": 		["Email:", "jb1988@gmail.com"],
		"date": 		["Date:", "2012-06-22"],
		"make": 		["Make:", "Toyota"],
		"car": 			["Car:", "Supra R"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "9's"],
		"hp": 			["Horse Power:", "800HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Looking for other female racers out there."]
	},
	"contact7": {
		"fname": 		["First Name:", "Chris"],
		"lname": 		["Last Name:", "Henderson"],
		"email": 		["Email:", "mrhenderson@sbcglobal.net"],
		"date": 		["Date:", "2012-06-24"],
		"make": 		["Make:", "Ford"],
		"car": 			["Car:", "Mustang GT"],
		"caramount": 	["How many cars do you own:", "1"],
		"fastest": 		["Fastest Time:", "10's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 2"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "No"],
		"comments": 	["Any Comments:", "Ford guy looking for tech advice."]
	},
	"contact8": {
		"fname": 		["First Name:", "Jay"],
		"lname": 		["Last Name:", "Butler"],
		"email": 		["Email:", "camaroguy99@gmail.com"],
		"date": 		["Date:", "2012-06-24"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Camaro SS"],
		"caramount": 	["How many cars do you own:", "4"],
		"fastest": 		["Fastest Time:", "10's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Direct Port"],
		"tranny": 		["Transmission:", "Auto"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Looking to buy some parts."]
	},
	"contact9": {
		"fname": 		["First Name:", "Derrick"],
		"lname": 		["Last Name:", "Bale"],
		"email": 		["Email:", "dbracer@aol.com"],
		"date": 		["Date:", "2012-06-25"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Corvette Z07"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "11's"],
		"hp": 			["Horse Power:", "600HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 2"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Corvette guy looking for some good o'le racing."]
	},
	"contact10": {
		"fname": 		["First Name:", "Jason"],
		"lname": 		["Last Name:", "Barrett"],
		"email": 		["Email:", "jason_b_99@yahoo.com"],
		"date": 		["Date:", "2012-06-25"],
		"make": 		["Make:", "Pontiac"],
		"car": 			["Car:", "TA"],
		"caramount": 	["How many cars do you own:", "1"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Need help getting into 11's"]
	},
	"contact11": {
		"fname": 		["First Name:", "Ray"],
		"lname": 		["Last Name:", "Biglsley"],
		"email": 		["Email:", "raytheman@gmail.com"],
		"date": 		["Date:", "2012-06-26"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Camaro"],
		"caramount": 	["How many cars do you own:", "3"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "500HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 2"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Anybody from Texas?"]
	},
	"contact12": {
		"fname": 		["First Name:", "Jesus"],
		"lname": 		["Last Name:", "Cassos"],
		"email": 		["Email:", "j_to_the_c@gmail.com"],
		"date": 		["Date:", "2012-06-26"],
		"make": 		["Make:", "Dodge"],
		"car": 			["Car:", "Viper AC"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "8's"],
		"hp": 			["Horse Power:", "900HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 2"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "No"],
		"comments": 	["Any Comments:", "No thanks!"]
	},
	"contact13": {
		"fname": 		["First Name:", "Kurt"],
		"lname": 		["Last Name:", "Brooking"],
		"email": 		["Email:", "kb@gmail.com"],
		"date": 		["Date:", "2012-06-26"],
		"make": 		["Make:", "Chevrolet"],
		"car": 			["Car:", "Corvette ZR1"],
		"caramount": 	["How many cars do you own:", "1"],
		"fastest": 		["Fastest Time:", "10's"],
		"hp": 			["Horse Power:", "600HP"],
		"adder": 		["Power Adder:", "Nitrous Direct Port"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Any fellow Vette guys from the south?"]
	},
	"contact14": {
		"fname": 		["First Name:", "Alex"],
		"lname": 		["Last Name:", "Bousey"],
		"email": 		["Email:", "bousey_south@yahoo.com"],
		"date": 		["Date:", "2012-06-26"],
		"make": 		["Make:", "Ford"],
		"car": 			["Car:", "AC Cobra"],
		"caramount": 	["How many cars do you own:", "4"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Looking to sell my Cobra"]
	},
	"contact15": {
		"fname": 		["First Name:", "Timothy"],
		"lname": 		["Last Name:", "Dalts"],
		"email": 		["Email:", "td1999@aol.com"],
		"date": 		["Date:", "2012-06-27"],
		"make": 		["Make:", "Pontiac"],
		"car": 			["Car:", "GTO SS"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "American Muscle"]
	},
	"contact16": {
		"fname": 		["First Name:", "Doug"],
		"lname": 		["Last Name:", "Bates"],
		"email": 		["Email:", "doug_bates_4599@aol.com"],
		"date": 		["Date:", "2012-06-27"],
		"make": 		["Make:", "Ferrari"],
		"car": 			["Car:", "455ci"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "11's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Italian Sports Guy looking for some races."]
	},
	"contact17": {
		"fname": 		["First Name:", "Landon"],
		"lname": 		["Last Name:", "Powell"],
		"email": 		["Email:", "lp_gt@gmail.com"],
		"date": 		["Date:", "2012-06-27"],
		"make": 		["Make:", "Nissan"],
		"car": 			["Car:", "GT-R"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "11's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Nitrous Stage 1"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "No"],
		"comments": 	["Any Comments:", "Any events in Florida?"]
	},
	"contact18": {
		"fname": 		["First Name:", "Matt"],
		"lname": 		["Last Name:", "Billings"],
		"email": 		["Email:", "typer_racer99@gmail.com"],
		"date": 		["Date:", "2012-06-28"],
		"make": 		["Make:", "Honda"],
		"car": 			["Car:", "Civic Type-R"],
		"caramount": 	["How many cars do you own:", "1"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "500HP"],
		"adder": 		["Power Adder:", "Twin Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "No"],
		"comments": 	["Any Comments:", "I love Cars"]
	},
	"contact19": {
		"fname": 		["First Name:", "Justin"],
		"lname": 		["Last Name:", "Case"],
		"email": 		["Email:", "case_racing@aol.com"],
		"date": 		["Date:", "2012-06-28"],
		"make": 		["Make:", "Toyota"],
		"car": 			["Car:", "Supra"],
		"caramount": 	["How many cars do you own:", "3"],
		"fastest": 		["Fastest Time:", "8's"],
		"hp": 			["Horse Power:", "800HP"],
		"adder": 		["Power Adder:", "Twin Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Any Supra guys?"]
	},
	"contact20": {
		"fname": 		["First Name:", "Mario"],
		"lname": 		["Last Name:", "Bustamante"],
		"email": 		["Email:", "ninesorbust@gmail.com"],
		"date": 		["Date:", "2012-06-28"],
		"make": 		["Make:", "Honda"],
		"car": 			["Car:", "Civic Type-R"],
		"caramount": 	["How many cars do you own:", "4"],
		"fastest": 		["Fastest Time:", "12's"],
		"hp": 			["Horse Power:", "400HP"],
		"adder": 		["Power Adder:", "Single Turbo"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Car show fanatic"]
	},
	"contact21": {
		"fname": 		["First Name:", "Gillie"],
		"lname": 		["Last Name:", "Fuller"],
		"email": 		["Email:", "mr_gillie_2488@aol.com"],
		"date": 		["Date:", "2012-06-28"],
		"make": 		["Make:", "Ford"],
		"car": 			["Car:", "Mustang Cobra R"],
		"caramount": 	["How many cars do you own:", "2"],
		"fastest": 		["Fastest Time:", "10's"],
		"hp": 			["Horse Power:", "600HP"],
		"adder": 		["Any Power Adders:", "Nitrous Stage 3"],
		"tranny": 		["Transmission:", "Manual"],
		"ltech": 		["Referred from LS1Tech.com:", "Yes"],
		"comments": 	["Any Comments:", "Who has parts for sale?"]
	}
}